# ~/.config/yazi/yazi.toml

[manager]
ratio = [2, 3, 4]
sort_dir_first = true
show_hidden = true
show_symlink = true

# yazi-rs/plugins:git

[[plugin.prepend_fetchers]]
id = 'git'
name = '*'
run = 'git'

[[plugin.prepend_fetchers]]
id = 'git'
name = '*/'
run = 'git'
